CREATE TABLE text (
  id varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL default '',
  label varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL default '',
  html TEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
  display_order int(11) NOT NULL default 0,
  update_date datetime NULL,
  update_user_id varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL,
  PRIMARY KEY  (id)
);

INSERT INTO text (id, label, display_order, html) VALUES
('introduction', 'Introduction', 1, '<h1>Welcome to the New Zealand Hearing Screening Test (NZHST).</h1><p>Do you have a hearing loss? This screening test is a quick and simple way to find out if you do. It tests how well you hear speech in noise, which can be one of the first things people with hearing loss notice.</p><p>Remember though, while its results are reliable, it doesn''t replace a professional evaluation by an audiologist - it''s intended only as a guide to let you know if you might need to consider seeking further assessment.</p><p>Please fill in the blanks below, plug in your headphones or a speaker, and then press ''start''</p>'),
('test', 'Sound Check - with speakers', 2, '<p>We recommend that you do this test in a quiet environment, and if you wear hearing aids, please remove them before beginning the test.</p><p>Please ensure your speakers are plugged in and switched on. You can test that they are working and that the volume level is correct by pressing the Check Volume button. Once you''re sure that your speakers are working, click the Start button to start the test.</p><p>You will hear three numbers spoken in a background noise. Once the presentation is finished, key in what you heard using the keyboard, or by selecting the numbers on the screen.</p><p>It may become quite difficult to hear what is said, but if you are unsure, take a guess! The test will not proceed until you have entered three digits and pressed ''Next''. If you make a mistake, press delete or backspace to alter your answer before continuing.</p>'),
('testl', 'Sound Check - left ear', 3, '<p>To perform this test you are required to wear earphones, so that the left and right ears can be tested separately. We recommend that you do this test in a quiet environment, and if you wear hearing aids, please remove them before beginning the test.</p><p>Please ensure your headphones are plugged in. You can test that they are working and that the volume level is correct by pressing the Check Volume button. Once you''re sure that your headphones are working, click the Start button to start the test.</p><p>You will hear three numbers spoken in a background noise. Once the presentation is finished, key in what you heard using the keyboard, or by selecting the numbers on the screen.</p><p>It may become quite difficult to hear what is said, but if you are unsure, take a guess! The test will not proceed until you have entered three digits and pressed ''Next''. If you make a mistake, press delete or backspace to alter your answer before continuing.</p><p>Your left ear will be tested first</p>'),
('testr', 'Sound Check - rigth ear', 4, '<p>Now your right ear will be tested. When you''re ready, press the Start button to start testing this ear.</p>'),
('result-2', 'Incomplete Result (speakers)', 5, '<p>Thank you.</p><p>Sorry, your test is incomplete, Click <a href="https://labbcat.canterbury.ac.nz/nzilbb/digittriplets">here</a> to try again.</p>'),
('resultl-2', 'Incomplete Result (left ear)', 6, '<p>Thank you.</p><p>Left ear:</p><p>Sorry, your test is incomplete, Click <a href="https://labbcat.canterbury.ac.nz/nzilbb/digittriplets">here</a> to try again.</p>'),
('resultr-2', 'Incomplete Result (right ear)', 7, '<p>Thank you.</p><p>Right Ear:</p><p>Sorry, your test is incomplete, Click <a href="https://labbcat.canterbury.ac.nz/nzilbb/digittriplets">here</a> to try again.</p>'),
('result-1', 'Poor Result (speakers)', 8, '<p>Thank you for using the New Zealand Hearing Screening Test.</p><p>Your hearing status: <strong>Poor</strong></p><p>The results indicate you may have hearing problems. It is advisable for you to see an audiologist for a more detailed assessment of your hearing.</p><p>Regardless of your result, protecting your hearing from further damage through loud and/or lengthy noise exposure is always worthwhile.</p><p>If you feel that your hearing is causing communication problems, please consult your nearest audiologist immediately. This test is not sensitive to some types of hearing problems - it is specially designed to test those with permanent hearing problems.</p><p><em>This test was developed by the New Zealand Institute of Language, Brain and Behavior at the University of Canterbury.</em></p>'),
('resultl-1', 'Poor Result (left ear)', 9, '<p>Thank you for trying the Hearing Screening Test</p><p>Left Ear:</p><p>Your hearing status: <strong>Poor</strong></p><p>You may have hearing problems with this ear. We recommend that you see your doctor or contact your nearest audiologist for further hearing test. Please be aware that you have run this test and have been recommended to run a more comprehensive hearing test. At the same time, you need to protect your hearing from noise that can make your hearing level worse. To learn more about how to protect your hearing, please click here.</p>'),
('resultr-1', 'Poor Result (right ear)', 10, '<p>Right ear:</p><p>Your hearing status: <strong>Poor</strong></p><p>You appear to have a hearing loss in this ear. We recommend you consult your GP, or contact an audiology clinic in your area to organise further testing. Mention that you have used a hearing-screening test that has indicated further investigation is worthwhile. In the meantime, it is important to protect your ears from noisy situations that can cause damage to your hearing ability. Learn about how you can take steps to safeguard your hearing <a href="http://www.nfd.org.nz/?t=58">here</a>.</p><p>Regardless of your hearing decision today, protecting your hearing from excessive noise is always a good practice.</p><p>If you feel that your hearing is causing communication problems, please consult your nearest audiologist immediately. This test is not sensitive to some types of hearing problems - it is specially designed to test those with permanent hearing problems. To learn more about hearing problems, please click here.</p><p><em>This test was developed by the New Zealand Institute of Language, Brain and Behavior, Canterbury University.</em></p>'),
('result0', 'Inconclusive Result (speakers)', 11, '<p>Thank you for trying Hearing Screening Test</p><p>Your hearing status: <strong>Inconclusive</strong></p><p>Your hearing is a little below normal. This is common and may be due to the level of noise around you. However, you are encouraged to consult an audiologist for a more comprehensive hearing test.<p>Regardless of your hearing decision today, protecting your hearing from excessive noise is always a good practice. To learn how to protect your hearing, please click here.</p><p>To find out how hearing problems can occur, please click here.</p><p><em>This test was developed by the New Zealand Institute of Language, Brain and Behavior, Canterbury University.</em></p>'),
('resultl0', 'Inconclusive Result (left ear)', 12, '<p>Thank you for trying Hearing Screening Test</p><p>Left Ear:</p><p>Your hearing status: <strong>Inconclusive</strong></p><p>Your hearing is a little below normal. This is common and may be due to the level of noise around you. However, you are encouraged to consult an audiologist for a more comprehensive hearing test.</p>'),
('resultr0', 'Inconclusive Result (right ear)', 13, '<p>Thank you for trying Hearing Screening Test</p><p>Right Ear:</p><p>Your hearing status: <strong>Inconclusive</strong></p><p>Your hearing is a little below normal. This is common and may be due to the level of noise around you. However, you are encouraged to consult an audiologist for a more comprehensive hearing test.</p><p>Regardless of your hearing decision today, protecting your hearing from excessive noise is always a good practice. To learn how to protect your hearing, please click here.</p><p>To find out how hearing problems can occur, please click here.</p><p><em>This test was developed by the New Zealand Institute of Language, Brain and Behavior, Canterbury University.</em></p>'),
('result1', 'Normal Result (speakers)', 14, '<p>Thank you for trying Hearing Screening Test</p><p>Your hearing level: <strong>Normal</strong></p><p>Congratulations! You have no hearing problems. However, it is advisable to check your hearing at least once in two years, or as soon as possible if you feel your hearing level has dropped. To learn how you can protect your hearing, click here.</p><p>If you feel that your hearing is causing communication problems, please consult your nearest audiologist immediately. This test is not sensitive to some types of hearing problems - it is specially designed to test those with permanent hearing problems. To learn more about hearing problems, please click here</p><p><em>This test was developed by the New Zealand Institute of Language, Brain and Behavior, Canterbury University.</em></p>'),
('resultl1', 'Normal Result (left ear)', 15, '<p>Thank you for trying Hearing Screening Test</p><p>Left Ear:</p><p>Your hearing level: <strong>Normal</strong></p><p>Congratulations! You have no hearing problems. However, it is advisable to check your hearing at least once in two years, or as soon as possible if you feel your hearing level has dropped. To learn how you can protect your hearing, click here.</p>'),
('resultr1', 'Normal Result (right ear)', 16, '<p>Thank you for trying Hearing Screening Test</p><p>Right Ear:</p><p>Your hearing level: <strong>Normal</strong></p><p>Congratulations! You have no hearing problems. However, it is advisable to check your hearing at least once in two years, or as soon as possible if you feel your hearing level has dropped. To learn how you can protect your hearing, click here.</p><p>If you feel that your hearing is causing communication problems, please consult your nearest audiologist immediately. This test is not sensitive to some types of hearing problems - it is specially designed to test those with permanent hearing problems. To learn more about hearing problems, please click here</p><p><em>This test was developed by the New Zealand Institute of Language, Brain and Behavior, Canterbury University.</em></p>');
